
server:
  port: 8080
  servlet:
    context-path: /spring-datajpa-cassandra

spring:
  config:
    import: classpath:/git-commit.properties

  output:
    ansi:
      enabled: always

  # Spring Cassandra Database Configuration
  data:
    cassandra:
      local-datacenter: datacenter1
      keyspace-name: emp_db_keyspace
      port: 9042
      username: cassandra
      password: cassandra
      schema-action: create_if_not_exists
      contact-points:
        - localhost:9042
        - 127.0.0.1:9042

application:
  log-level: info
  log-file-dir: logs/

